#!/usr/bin/env python3
"""
homepage_publish_check.py — verifies the LIVE homepage (themakeupblowout.com)
is actually showing the current/next event, and writes docs/state/homepage_status.json.

Why: themakeupblowout.com is a Lovable-hosted site. Pushing schedule-data.ts to
the beauty-bash-usa repo SYNCS into Lovable but only goes live when someone clicks
Publish in the Lovable editor (Lovable does NOT auto-publish — verified 2026-06-01).
The 🏠 Home Page button on the launch dashboard reads this file: GREEN when the live
hero already shows the current event (published & up to date), BLACK when it's stale
(Lauren still needs to open Lovable and click Publish).

The page is server-side-rendered (TanStack Start), so the hero text is present in the
raw HTML and we can read it with a plain GET — no headless browser needed.

Expected current event = first upcoming event (end_date >= today PT) in
docs/state/upcoming_events.json, sorted by start_date.

No secrets needed. Pure read + compute + write JSON.
"""
import json, re, datetime, urllib.request
from pathlib import Path
from zoneinfo import ZoneInfo

HOMEPAGE = "https://www.themakeupblowout.com/"
UPCOMING = Path("docs/state/upcoming_events.json")
OUT      = Path("docs/state/homepage_status.json")

def slugify(c): return re.sub(r"[^a-z0-9]+", "-", (c or "").lower()).strip("-")

def fetch_html(url):
    req = urllib.request.Request(url + ("&" if "?" in url else "?") + "_cb=" + str(int(datetime.datetime.now().timestamp())),
                                 headers={"User-Agent": "MBS-homepage-check/1.0", "Cache-Control": "no-cache"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read().decode("utf-8", "replace")

def extract_hero(html):
    """Return (city, state, raw_text) from the hero 'This Weekend <City>, <ST> · <dates>'."""
    text = re.sub(r"<[^>]+>", " ", html)          # strip tags
    text = re.sub(r"\s+", " ", text)               # collapse whitespace
    m = re.search(r"This Weekend\s+([A-Za-z .\/']+?),\s*([A-Z]{2})\s*[·\-–]\s*([A-Za-z0-9 –\-]+?)\b(?:#|MAKEUP|$)", text)
    if not m:
        # looser fallback: just city, ST after "This Weekend"
        m = re.search(r"This Weekend\s+([A-Za-z .\/']+?),\s*([A-Z]{2})", text)
        if not m:
            return None, None, None
        return m.group(1).strip(), m.group(2).strip(), f"{m.group(1).strip()}, {m.group(2).strip()}"
    city, st, dates = m.group(1).strip(), m.group(2).strip(), m.group(3).strip()
    return city, st, f"{city}, {st} · {dates}"

def expected_event():
    data = json.loads(UPCOMING.read_text(encoding="utf-8"))
    evs = data.get("events", []) if isinstance(data, dict) else data
    today = datetime.datetime.now(ZoneInfo("America/Los_Angeles")).date()
    up = [e for e in evs if datetime.date.fromisoformat(e["end_date"]) >= today]
    up.sort(key=lambda x: x["start_date"])
    return up[0] if up else None

def main():
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    exp = expected_event()
    status = {
        "_doc": "Auto-generated by .github/workflows/homepage-publish-check.yml. Read by the 🏠 Home Page button on the launch dashboard. is_current=true => live homepage hero already shows the current event (published). Do not edit by hand.",
        "checked_at": now,
        "homepage": HOMEPAGE,
        "expected_event_key": exp["event_key"] if exp else None,
        "expected_label": (f'{exp["city"]}, {exp["state"]}' if exp else None),
        "live_city": None, "live_state": None, "live_hero_text": None,
        "is_current": False,
        "fetch_ok": False,
    }
    try:
        html = fetch_html(HOMEPAGE)
        status["fetch_ok"] = True
        city, st, raw = extract_hero(html)
        status["live_city"], status["live_state"], status["live_hero_text"] = city, st, raw
        if exp and city and st:
            status["is_current"] = (slugify(city) == slugify(exp["city"]) and st.upper() == exp["state"].upper())
    except Exception as e:
        status["error"] = str(e)
        print("fetch/parse error:", e)

    OUT.write_text(json.dumps(status, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"wrote {OUT}: is_current={status['is_current']} live='{status['live_hero_text']}' expected='{status['expected_label']}'")

if __name__ == "__main__":
    main()
