#!/usr/bin/env python3
"""
update_subscribe_target.py

Picks the current OR next-upcoming event from launch/index.html's SCHEDULE map,
joins it with SETUPS (SimpleTexting list_id), event_form_ids.json (webForm ID),
and launch/notes.json (per-event Reel URL), and writes
docs/state/subscribe_target.json - consumed cross-origin by the
public landing page at https://www.themakeupblowoutsale-group.com/subscribe-list/

Source of truth lives in launch/index.html (SCHEDULE/SETUPS) and
docs/state/event_form_ids.json. We never duplicate event data - we just
publish a thin pointer to "the relevant one right now".
"""

import datetime, json, re, sys
from pathlib import Path

ROOT = Path(".")
LAUNCH    = ROOT / "docs/launch/index.html"
NOTES     = ROOT / "docs/launch/notes.json"
FORM_IDS  = ROOT / "docs/state/event_form_ids.json"
TARGET    = ROOT / "docs/state/subscribe_target.json"

DEFAULT_FB = "https://www.facebook.com/themakeupblowoutsale/"
DEFAULT_TT = "https://www.tiktok.com/@makeupblowoutsale"
DEFAULT_IG = "https://www.instagram.com/makeupblowoutsale/"


def slug_of(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", (s or "").lower()).strip("-")


def parse_map(html: str, name: str) -> dict:
    m = re.search(rf"const {name} = (\{{[^;]+\}});", html, re.S)
    return json.loads(m.group(1)) if m else {}


def today_pt() -> datetime.date:
    """Return today's date in America/Los_Angeles. cron runs in UTC."""
    try:
        from zoneinfo import ZoneInfo
        return datetime.datetime.now(ZoneInfo("America/Los_Angeles")).date()
    except Exception:
        # Approximate fallback - UTC minus 7h (PDT) or 8h (PST). Worst case
        # we pick the wrong event for ~1h on a day-boundary.
        return (datetime.datetime.utcnow() - datetime.timedelta(hours=7)).date()


def main() -> int:
    if not LAUNCH.exists():
        print(f"ERR: {LAUNCH} not found", file=sys.stderr)
        return 1

    html      = LAUNCH.read_text(encoding="utf-8")
    SCHEDULE  = parse_map(html, "SCHEDULE")
    SETUPS    = parse_map(html, "SETUPS")
    notes     = json.loads(NOTES.read_text(encoding="utf-8")) if NOTES.exists() else {}
    form_ids_root = json.loads(FORM_IDS.read_text(encoding="utf-8")) if FORM_IDS.exists() else {}
    form_ids  = form_ids_root.get("events", {}) if isinstance(form_ids_root, dict) else {}

    today = today_pt()

    # Flatten events from year-keyed lists (skip _baked_at and other meta keys)
    all_events = []
    for year, lst in SCHEDULE.items():
        if not (isinstance(lst, list) and year.isdigit()):
            continue
        for ev in lst:
            sd = ev.get("start_date")
            if not sd:
                continue
            all_events.append({**ev, "_ed": ev.get("end_date") or sd})

    # Pick: prefer "today is between start_date and end_date" (event is LIVE),
    # otherwise the earliest event whose start_date is >= today.
    def parse(s): return datetime.date.fromisoformat(s)
    current = None
    upcoming = []
    for ev in all_events:
        try:
            sd, ed = parse(ev["start_date"]), parse(ev["_ed"])
        except Exception:
            continue
        if sd <= today <= ed:
            current = ev
            break
        if sd >= today:
            upcoming.append((sd, ev))
    upcoming.sort(key=lambda x: x[0])

    picked = current or (upcoming[0][1] if upcoming else None)
    if not picked:
        print("ERR: no current or upcoming events found in SCHEDULE", file=sys.stderr)
        return 1

    city_slug  = slug_of(picked["city"])
    state_lc   = (picked.get("state") or "").lower()
    year_str   = picked["start_date"][:4]
    setups_key = f"{city_slug}-{picked['start_date']}"
    form_key   = f"{city_slug}-{state_lc}-{year_str}-{picked['start_date']}"

    setup = SETUPS.get(setups_key) or {}
    form  = form_ids.get(form_key) or {}
    note  = notes.get(setups_key) or {}

    smslist = setup.get("smslist") or {}

    target = {
        "_doc": (
            "Auto-generated by .github/workflows/update-subscribe-target.yml. "
            "Picks current/next event for the public /subscribe-list/ landing page on "
            "themakeupblowoutsale-group.com. Do not edit by hand."
        ),
        "_updated_at": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "event_key":   setups_key,
        "form_key":    form_key,
        "city":        picked["city"],
        "state":       picked.get("state", ""),
        "start_date":  picked["start_date"],
        "end_date":    picked.get("end_date") or picked["start_date"],
        "venue":       picked.get("venue", ""),
        "address":     picked.get("address", ""),
        "is_live":     bool(current),
        "form_id":     form.get("form_id"),
        "form_url":    form.get("form_url"),
        "list_id":     smslist.get("list_id"),
        "list_name":   smslist.get("list_name"),
        "ig_reel_url": note.get("insta_reel_url") or DEFAULT_IG,
        "fb_url":      DEFAULT_FB,
        "tiktok_url":  DEFAULT_TT,
    }

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(json.dumps(target, indent=2, ensure_ascii=False))
    n = TARGET.stat().st_size
    print(f"wrote {TARGET} ({n}B): event_key={target['event_key']} "
          f"is_live={target['is_live']} form_id={target['form_id']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
